### PR TITLE
A set of improvements suggested by BA & EvD

### PR DESCRIPTION
**Pull request by gmerritt**
- shared directory (not shared-writeable) 
- report run time for all cells
- "try" for %pip installs
- ls shared models directory

### CODE REVIEW

**Comment by balajialg** [comment]
wow, that's awesome @gmerritt

**Comment by gmerritt** [comment]
@balajialg @ericvd-ucb -- Can you accept this PR? Is it ok?

Thanks!

**Review by balajialg — APPROVED** [review]
LGTM

**Comment by balajialg** [comment]
Merging changes

**Pull request merged**
